// src/services/exportService.js
const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph, HeadingLevel, AlignmentType } = require("docx");
const PptxGenJS = require("pptxgenjs");

async function generateMoMPDF(mom) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc    = new PDFDocument({ size: "A4", margin: 60, info: { Title: mom.title || "MoM" } });
    doc.on("data", c => chunks.push(c));
    doc.on("end",  () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const W = doc.page.width - 120;
    const AMBER = "#f5a623";

    // Header band
    doc.rect(0, 0, doc.page.width, 90).fill("#060c1a");
    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(16)
       .text("GOVERNMENT OF TELANGANA", 60, 24, { width: W, align: "center" });
    doc.fillColor(AMBER).fontSize(12)
       .text("DISTRICT HEALTH DEPARTMENT", 60, 46, { width: W, align: "center" });
    doc.fillColor("#94a3b8").fontSize(10).font("Helvetica")
       .text("MeetIQ AI — Official Minutes of Meeting", 60, 66, { width: W, align: "center" });

    doc.moveDown(4);

    // Title
    doc.fillColor(AMBER).font("Helvetica-Bold").fontSize(15)
       .text("MINUTES OF MEETING", 60, doc.y, { width: W, align: "center" });
    doc.fillColor("#1e293b").fontSize(12).font("Helvetica")
       .text(mom.title || "Meeting Title", 60, doc.y + 6, { width: W, align: "center" });

    doc.moveDown(1.5);
    doc.moveTo(60, doc.y).lineTo(60 + W, doc.y).strokeColor(AMBER).lineWidth(1.5).stroke();
    doc.moveDown(1);

    // Metadata
    for (const [k, v] of [
      ["Date",       mom.started_at ? new Date(mom.started_at).toDateString() : "—"],
      ["Venue",      mom.venue || "—"],
      ["Chaired By", mom.chaired_by || "—"],
    ]) {
      doc.fillColor("#64748b").font("Helvetica-Bold").fontSize(9)
         .text(`${k.toUpperCase()}: `, 60, doc.y, { continued: true });
      doc.fillColor("#1e293b").font("Helvetica").fontSize(10).text(v);
    }

    doc.moveDown(0.8);

    // Sections helper
    const sect = (title, items, fmt) => {
      doc.fillColor(AMBER).font("Helvetica-Bold").fontSize(11).text(title, 60);
      doc.moveTo(60, doc.y).lineTo(60 + W, doc.y).strokeColor(AMBER).lineWidth(0.5).stroke();
      doc.moveDown(0.4);
      (items || []).forEach((item, i) => {
        const text = typeof item === "string" ? item : (item.decision || item.task || item.item || JSON.stringify(item));
        doc.fillColor("#1e293b").font("Helvetica").fontSize(10)
           .text(`  ${i + 1}. ${text}`, 72);
      });
      if (!(items || []).length) doc.fillColor("#999").text("  —", 72);
      doc.moveDown(0.8);
    };

    sect("1. DECISIONS TAKEN",      mom.decisions     || []);
    sect("2. ACTION ITEMS",         mom.action_items  || []);
    sect("3. AGENDA ITEMS COVERED", mom.agenda_items  || []);

    // Footer
    const remaining = doc.page.height - doc.y - 60;
    if (remaining < 40) doc.addPage();
    doc.fontSize(8).fillColor("#94a3b8")
       .text(
         `Auto-generated by MeetIQ AI on ${new Date().toDateString()} · CONFIDENTIAL · District use only`,
         60, doc.page.height - 40, { width: W, align: "center" }
       );

    doc.end();
  });
}

async function generateMoMDOCX(data) {
  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ text: "MINUTES OF MEETING", heading: HeadingLevel.TITLE, alignment: AlignmentType.CENTER }),
        new Paragraph({ text: data.title || "Meeting", alignment: AlignmentType.CENTER }),
        new Paragraph({ text: "" }),
        new Paragraph({ text: "DECISIONS", heading: HeadingLevel.HEADING_1 }),
        ...(data.decisions || []).map(d =>
          new Paragraph({ text: `• ${typeof d === "string" ? d : d.decision || d}` })
        ),
        new Paragraph({ text: "" }),
        new Paragraph({ text: "ACTION ITEMS", heading: HeadingLevel.HEADING_1 }),
        ...(data.action_items || data.actions || []).map((a, i) =>
          new Paragraph({
            text: `${i + 1}. ${a.task || a} — ${a.assigned_name || a.assigned_to || "—"} — Due: ${a.due_date || "—"}`,
          })
        ),
        new Paragraph({ text: "" }),
        new Paragraph({ text: `Auto-generated by MeetIQ AI on ${new Date().toDateString()}` }),
      ],
    }],
  });
  return Packer.toBuffer(doc);
}

async function generateMoMPPTX(data) {
  const pptx = new PptxGenJS();

  // Title slide
  const s1 = pptx.addSlide();
  s1.background = { color: "060c1a" };
  s1.addText("MINUTES OF MEETING", { x: 0.5, y: 1.8, w: 9, h: 1, fontSize: 30, bold: true, color: "f5a623", align: "center" });
  s1.addText(data.title || "Meeting Title", { x: 0.5, y: 3.0, w: 9, h: 0.6, fontSize: 16, color: "e8edf7", align: "center" });
  s1.addText(`MeetIQ AI  ·  ${new Date().toDateString()}`, { x: 0.5, y: 6.5, w: 9, h: 0.4, fontSize: 10, color: "475569", align: "center" });

  // Decisions slide
  if ((data.decisions || []).length) {
    const s2 = pptx.addSlide();
    s2.background = { color: "0d1528" };
    s2.addText("DECISIONS TAKEN", { x: 0.5, y: 0.3, w: 9, h: 0.7, fontSize: 22, bold: true, color: "f5a623" });
    (data.decisions || []).forEach((d, i) => {
      const text = typeof d === "string" ? d : d.decision || d;
      s2.addText(`${i + 1}.  ${text}`, { x: 0.5, y: 1.2 + i * 0.65, w: 9, h: 0.6, fontSize: 12, color: "e2e8f0" });
    });
  }

  // Action items slide
  const actions = data.action_items || data.actions || [];
  if (actions.length) {
    const s3 = pptx.addSlide();
    s3.background = { color: "0d1528" };
    s3.addText("ACTION ITEMS", { x: 0.5, y: 0.3, w: 9, h: 0.7, fontSize: 22, bold: true, color: "f5a623" });
    const tableRows = [
      [{ text: "#" }, { text: "Task" }, { text: "Officer" }, { text: "Due" }, { text: "Priority" }],
      ...actions.slice(0, 10).map((a, i) => [
        String(i + 1), a.task || "—", a.assigned_name || "—", a.due_date || "—", a.priority || "medium",
      ]),
    ];
    s3.addTable(tableRows, {
      x: 0.3, y: 1.2, w: 9.4,
      colW: [0.4, 4.5, 2.2, 1.3, 1.0],
      border:   { type: "solid", color: "1e2d4a" },
      color:    "e2e8f0",
      fontSize: 9,
    });
  }

  return Buffer.from(await pptx.stream());
}

module.exports = { generateMoMPDF, generateMoMDOCX, generateMoMPPTX };
