// src/services/notificationService.js
const sgMail      = require("@sendgrid/mail");
const TelegramBot = require("node-telegram-bot-api");
const twilio      = require("twilio");
const logger      = require("../config/logger");

if (process.env.SENDGRID_API_KEY) sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const telegramBot = process.env.TELEGRAM_BOT_TOKEN
  ? new TelegramBot(process.env.TELEGRAM_BOT_TOKEN)
  : null;

const twilioClient = (process.env.TWILIO_ACCOUNT_SID && process.env.TWILIO_AUTH_TOKEN)
  ? twilio(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN)
  : null;

// ─── Email ────────────────────────────────────────────────────
async function sendEmail({ to, subject, html, text }) {
  if (!process.env.SENDGRID_API_KEY) {
    logger.debug(`[Email Mock] To:${to} | Subject:${subject}`);
    return;
  }
  await sgMail.send({
    to, subject,
    html: html || `<p>${text || ""}</p>`,
    from: {
      email: process.env.FROM_EMAIL || "noreply@meetiq.ai",
      name:  process.env.FROM_NAME  || "MeetIQ AI",
    },
  });
}

// ─── Telegram ─────────────────────────────────────────────────
async function sendTelegram(chatId, message) {
  if (!telegramBot) {
    logger.debug(`[Telegram Mock] ${chatId}: ${message}`);
    return;
  }
  await telegramBot.sendMessage(chatId, message, { parse_mode: "Markdown" });
}

// ─── WhatsApp (Twilio) ────────────────────────────────────────
async function sendWhatsApp(to, message) {
  if (!twilioClient) {
    logger.debug(`[WhatsApp Mock] ${to}: ${message}`);
    return;
  }
  await twilioClient.messages.create({
    body: message,
    from: `whatsapp:${process.env.TWILIO_WHATSAPP_FROM}`,
    to:   `whatsapp:${to}`,
  });
}

// ─── Email Templates ──────────────────────────────────────────
function emailTemplate(type, data) {
  const wrap = (inner) => `
    <div style="font-family:Arial,sans-serif;background:#060c1a;color:#e8edf7;
                padding:40px;max-width:600px;margin:auto;border-radius:12px">
      <div style="text-align:center;margin-bottom:28px">
        <div style="background:linear-gradient(135deg,#f5a623,#e8891a);
                    display:inline-block;width:48px;height:48px;border-radius:12px;
                    font-size:24px;line-height:48px">🧠</div>
        <div style="font-size:22px;font-weight:800;color:#f5a623;margin-top:8px">MeetIQ AI</div>
      </div>
      ${inner}
      <div style="margin-top:32px;padding-top:16px;border-top:1px solid #1e2d4a;
                  font-size:11px;color:#3d5070;text-align:center">
        Auto-generated by MeetIQ AI · Confidential
      </div>
    </div>`;

  if (type === "meeting_processed") {
    return wrap(`
      <h2 style="color:#00d4ff">✅ Meeting Processed Successfully</h2>
      <p>Hello ${data.user?.full_name || "Officer"},</p>
      <p>Your meeting <strong style="color:#f5a623">${data.meeting?.title || ""}</strong>
         has been fully processed by AI.</p>
      <div style="background:#111d35;border-radius:8px;padding:16px;
                  margin:16px 0;border:1px solid #1e2d4a">
        <div style="margin-bottom:6px">📝 Transcript ready</div>
        <div style="margin-bottom:6px">✦ AI Summary (English + Telugu)</div>
        <div style="margin-bottom:6px">📋 Minutes of Meeting created</div>
        <div>◈ Action items extracted &amp; assigned</div>
      </div>
      <a href="${process.env.FRONTEND_URL}/meetings/${data.meeting?.id || ""}"
         style="background:#f5a623;color:#000;padding:12px 24px;
                border-radius:8px;text-decoration:none;font-weight:700;display:inline-block">
        View Full Report →
      </a>`);
  }

  if (type === "action_reminder") {
    return wrap(`
      <h2 style="color:#f5a623">⏰ Action Item Reminder</h2>
      <div style="background:#111d35;border-radius:8px;padding:16px;
                  border:1px solid #2a3f6a">
        <div style="font-size:15px;font-weight:600">${data.action?.task || ""}</div>
        <div style="color:#ff4757;margin-top:8px">Due: ${data.action?.due_date || "—"}</div>
        <div style="color:#7a8fb5;margin-top:4px">Priority: ${data.action?.priority || "—"}</div>
        <div style="color:#7a8fb5">Assigned to: ${data.action?.assigned_name || "—"}</div>
      </div>`);
  }

  return wrap(`<pre style="color:#aaa;font-size:12px">${JSON.stringify(data, null, 2)}</pre>`);
}

module.exports = { sendEmail, sendTelegram, sendWhatsApp, emailTemplate };
